name: manage-azure-policy-2ba5ac87
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Configure_Linux_virtual_machines_with_Azure_Monitor_Agent_a4034bc6-ae50-406d-bf76-50f4ee5a7811/**'
#      - .github/workflows/manage-azure-policy-2ba5ac87.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_2ba5ac87}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Configure_Linux_virtual_machines_with_Azure_Monitor_Agent_a4034bc6-ae50-406d-bf76-50f4ee5a7811/**
